version: '3'
services:
  server:
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - "4000:4000"
  client:
    build: ./client
    depends_on:
      - server
    ports:
      - "5173:80"
